#!/bin/sh

PATH="$HOME/.config/via:$PATH"

case "$1" in
	-r)  # rebuild cache first
		xdg-open "$(via-feed -r | via-menu )"
		;;
	-ro) # rebuild cache only
		via-feed -r >/dev/null
		;;
	*)
		xdg-open "$(via-feed | via-menu )"
		;;
esac
